/**
 * 手写简易 Git Hook 管理器
 *
 * 功能：管理 git hooks，在代码提交/推送时自动执行检查
 * 实现思路：
 *   1. 在 .git/hooks/ 目录创建 hook 脚本
 *   2. 支持 pre-commit、commit-msg、pre-push 等
 *   3. hook 脚本执行失败则中断 git 操作
 */

const fs = require('fs');
const path = require('path');

class GitHookManager {
  constructor(rootDir) {
    this.rootDir = rootDir || process.cwd();
    this.hooksDir = path.join(this.rootDir, '.git', 'hooks');
    this.hooks = new Map();
  }

  // 注册 hook
  register(name, commands) {
    this.hooks.set(name, commands);
  }

  // 安装 hook
  install(name) {
    const commands = this.hooks.get(name);
    if (!commands) throw new Error('Hook not registered: ' + name);
    const script = '#!/bin/sh\n# Auto-generated by GitHookManager\n' + commands.map(c => 'echo "[hook:' + name + '] running: ' + c + '"\n' + c).join('\n') + '\n';
    // 模拟写入（实际需要写入 .git/hooks/ 目录）
    console.log('[HookManager] Installing hook:', name);
    console.log('  Script:');
    console.log(script.split('\n').map(l => '    ' + l).join('\n'));
    return script;
  }

  // 安装所有 hooks
  installAll() {
    for (const name of this.hooks.keys()) this.install(name);
  }

  // 卸载 hook
  uninstall(name) {
    console.log('[HookManager] Uninstalling hook:', name);
    this.hooks.delete(name);
  }

  // 执行 hook（模拟）
  run(name) {
    const commands = this.hooks.get(name);
    if (!commands) return true;
    console.log('[HookManager] Running hook:', name);
    for (const cmd of commands) {
      console.log('  $', cmd);
      // 模拟执行结果
      if (cmd.includes('fail')) { console.log('  FAILED'); return false; }
      console.log('  OK');
    }
    return true;
  }
}

// ===== 测试 =====
const manager = new GitHookManager();
manager.register('pre-commit', ['npm run lint', 'npm test']);
manager.register('commit-msg', ['node scripts/validate-commit-msg.js']);
manager.register('pre-push', ['npm run build', 'npm test']);

console.log('=== 安装所有 hooks ===');
manager.installAll();

console.log('\n=== 模拟执行 pre-commit ===');
const passed = manager.run('pre-commit');
console.log('pre-commit passed:', passed); // true

console.log('\n=== 模拟执行失败的 hook ===');
manager.register('pre-commit', ['npm run lint', 'npm run fail:check', 'npm test']);
const failed = manager.run('pre-commit');
console.log('pre-commit passed:', failed); // false
