/**
 * _.mapKeys(object, [iteratee=_.identity])
 *
 * The opposite of _.mapValues; creates an object with the same values as
 * `object` and keys generated by running each own enumerable property
 * through `iteratee`. The iteratee is invoked with (value, key, object).
 * Iteratee may be a function or a property-name shorthand (lodash also
 * supports the string shorthand that plucks a property from the value).
 *
 * Approach:
 * - Iterate over the object's own keys.
 * - Compute the new key via the iteratee; cast to string for the result key.
 * - Assign the original value to the new key.
 */

function mapKeys(object, iteratee = (v) => v) {
  if (object == null) return {};
  const get =
    typeof iteratee === "function"
      ? iteratee
      : (v) => (v == null ? undefined : v[iteratee]);
  const result = {};
  for (const key of Object.keys(object)) {
    const newKey = String(get(object[key], key, object));
    result[newKey] = object[key];
  }
  return result;
}

// --- Tests ---

console.log(
  "mapKeys function:",
  JSON.stringify(mapKeys({ a: 1, b: 2 }, (value, key) => key + value)),
); // expected: {"a1":1,"b2":2}
console.log(
  "mapKeys prefix:",
  JSON.stringify(mapKeys({ x: 10, y: 20 }, (value) => "key_" + value)),
); // expected: {"key_10":10,"key_20":20}
console.log(
  "mapKeys shorthand:",
  JSON.stringify(mapKeys({ a: { id: 1 }, b: { id: 2 } }, "id")),
); // expected: {"1":{"id":1},"2":{"id":2}}
console.log(
  "mapKeys default identity:",
  JSON.stringify(mapKeys({ a: 1, b: 2 })),
); // expected: {"a":1,"b":2}
console.log("mapKeys null:", JSON.stringify(mapKeys(null))); // expected: {}
console.log(
  "mapKeys to numeric string:",
  JSON.stringify(mapKeys({ a: 1 }, () => 5)),
); // expected: {"5":1}
