/**
 * _.mapValues(object, [iteratee=_.identity])
 *
 * Creates an object with the same keys as `object` and values generated by
 * running each own enumerable property value through `iteratee`. The
 * iteratee is invoked with (value, key, object). Iteratee may be a function
 * or a property-name shorthand.
 *
 * Approach:
 * - Iterate over the object's own keys.
 * - Compute the new value via the iteratee and keep the same key.
 */

function mapValues(object, iteratee = (v) => v) {
  if (object == null) return {};
  const get =
    typeof iteratee === 'function'
      ? iteratee
      : (v) => (v == null ? undefined : v[iteratee]);
  const result = {};
  for (const key of Object.keys(object)) {
    result[key] = get(object[key], key, object);
  }
  return result;
}

// --- Tests ---

const users = {
  fred: { user: 'fred', age: 40 },
  pebbles: { user: 'pebbles', age: 1 },
};

console.log('mapValues function:', JSON.stringify(mapValues(users, (o) => o.age))); // expected: {"fred":40,"pebbles":1}
console.log('mapValues shorthand:', JSON.stringify(mapValues(users, 'age'))); // expected: {"fred":40,"pebbles":1}
console.log('mapValues square:', JSON.stringify(mapValues({ a: 1, b: 2, c: 3 }, (n) => n * n))); // expected: {"a":1,"b":4,"c":9}
console.log('mapValues default identity:', JSON.stringify(mapValues({ a: 1, b: 2 }))); // expected: {"a":1,"b":2}
console.log('mapValues null:', JSON.stringify(mapValues(null))); // expected: {}
console.log('mapValues with key:', JSON.stringify(mapValues({ a: 1, b: 2 }, (v, k) => k + ':' + v))); // expected: {"a":"a:1","b":"b:2"}
